### ISSUE TITLE
[Docs]input_files/SUEWS_SiteInfo/SUEWS_AnthropogenicEmission

### ISSUE THREAD

**Issue by RussellGl** [UMEP-dev/SUEWS#138]
## Issue

What is a default set of values for the anthropogenic emission? Say I only want to change the energy use profile code, what should I use for the rest of the coefficients?
## Links
[source doc](https://github.com/UMEP-dev/SUEWS/blob/master/docs/source/input_files/SUEWS_SiteInfo/SUEWS_AnthropogenicEmission.rst)
[RTD page](https://suews.readthedocs.org/en/latest/input_files/SUEWS_SiteInfo/SUEWS_AnthropogenicEmission.html)

**Comment by sunt05** [comment]
Closing as not planned - this issue relates to the deprecated table-based input format.

The table-based format () has been deprecated as of 2025 and will be removed by end of 2025. We are not improving documentation for deprecated formats.

**For anthropogenic emission configuration, please use the modern YAML format:**

In YAML, anthropogenic emissions are configured under the  section:

```yaml
anthropogenic_emissions:
  heat:
    qf_a:
      working_day: 0.3743
      holiday: 0.3412
    qf_b:
      working_day: 0.0
      holiday: 0.0
    qf_c:
      working_day: 0.0073
      holiday: 0.0067
    ahprof_24hr:
      working_day:
        '1': 0.57
        '2': 0.45
        # ... etc
```

**Resources:**
- YAML format guide: https://suews.readthedocs.org/en/latest/input_files/yaml/index.html
- Sample configuration: Check  in the supy sample data
- Migration guide: https://suews.readthedocs.org/en/latest/input_files/transition_guide.html
