### ISSUE TITLE
`model` part from `to_yaml` produces incorrect conversion

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/SUEWS#336]
Using the build from https://github.com/UMEP-dev/SUEWS/tree/sunt05/issue309:
```
from supy.util._config import SUEWSConfig
config_suews = SUEWSConfig.from_df_state(df_state_init)
config_suews.model
config_suews.to_yaml('quick-test.yml')
```

will produce incorrect conversion result with garbled results.

The following snippet shows the incorrect results in the `model.control` section:

```
name: sample config
description: this is a sample config for testing purposes ONLY - values are not realistic
model:
  control:
    tstep: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      LAEAAAAAAAA=
    forcing_file:
      value: forcing.txt
    output_file: output.txt
    diagnose: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAAAAA=
```
