### ISSUE TITLE
Error in yml-file (maybe)

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/SUEWS#407]
There is a dash (-) before the **name** key (in site key) which makes it into a list and not a dictionary. This make it hard to access all the parameters by e.g. `yaml_dict['site']['properties']['lat']`. Am I missing something or is this a typo?

```
name: sample config
description: this is a sample config for testing purposes ONLY - values are not realistic
model:
  control:
    tstep: 300
    forcing_file:
      value: Input/Kc_2012_data_60.txt
    output_file: output.txt
    diagnose: 0
  physics:
    netradiationmethod:
      value: 3
    emissionsmethod:
      value: 2
    storageheatmethod:
      value: 1
    ohmincqf:
      value: 0
    roughlenmommethod:
      value: 2
    roughlenheatmethod:
      value: 2
    stabilitymethod:
      value: 3
    smdmethod:
      value: 0
    waterusemethod:
      value: 0
    diagmethod:
      value: 2
    faimethod:
      value: 0
    localclimatemethod:
      value: 0
    snowuse:
      value: 0
    stebbsmethod:
      value: 0
site:
- name: test site
  gridiv: 1
```
